/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poo.trabajo.interfaces;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author josed y maria
 */

/**
 * 
 * Página donde se muestrna todas las opciones que puede relazar el cliente
 */
public class EsCliente extends javax.swing.JFrame {
    int xMouse,yMouse;
    /**
     * Creates new form EsCliente
     */
    public EsCliente() {
        initComponents();
        BusquedaProductos bp= new BusquedaProductos();//definimos la pantalla a mostrar
        bp.setSize(850, 550);
        bp.setLocation(0, 0);
        
        jPanelContenido.removeAll();
        jPanelContenido.add(bp,BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
        jLabelLogo.setIcon(new ImageIcon("./src/main/java/poo/trabajo/imagenes/javacomp1.png"));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelNavegador = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelDatos = new javax.swing.JLabel();
        jLabelCompra = new javax.swing.JLabel();
        jLabelInicio = new javax.swing.JLabel();
        jLabelCompra1 = new javax.swing.JLabel();
        jPanelIheader = new javax.swing.JPanel();
        jPanelBoton = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(844, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNavegador.setBackground(new java.awt.Color(255, 0, 0));

        jLabelLogo.setText("jLabelLogo");

        jLabelDatos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDatos.setText(" MI CUENTA");
        jLabelDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDatosMouseClicked(evt);
            }
        });

        jLabelCompra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCompra.setText("    CARRO");
        jLabelCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCompraMouseClicked(evt);
            }
        });

        jLabelInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelInicio.setText("     INICIO");
        jLabelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInicioMouseClicked(evt);
            }
        });

        jLabelCompra1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCompra1.setText("   OPINAR");
        jLabelCompra1.setToolTipText("");
        jLabelCompra1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCompra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCompra1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelNavegadorLayout = new javax.swing.GroupLayout(jPanelNavegador);
        jPanelNavegador.setLayout(jPanelNavegadorLayout);
        jPanelNavegadorLayout.setHorizontalGroup(
            jPanelNavegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
            .addComponent(jLabelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabelCompra1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelNavegadorLayout.setVerticalGroup(
            jPanelNavegadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavegadorLayout.createSequentialGroup()
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 256, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelNavegador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, 550));

        jPanelIheader.setBackground(new java.awt.Color(51, 51, 255));
        jPanelIheader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelIheaderMouseDragged(evt);
            }
        });
        jPanelIheader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelIheaderMousePressed(evt);
            }
        });

        jLabelCerrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCerrar.setText("X");
        jLabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonLayout = new javax.swing.GroupLayout(jPanelBoton);
        jPanelBoton.setLayout(jPanelBotonLayout);
        jPanelBotonLayout.setHorizontalGroup(
            jPanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBotonLayout.setVerticalGroup(
            jPanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCerrar))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("LOGOUT");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelIheaderLayout = new javax.swing.GroupLayout(jPanelIheader);
        jPanelIheader.setLayout(jPanelIheaderLayout);
        jPanelIheaderLayout.setHorizontalGroup(
            jPanelIheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIheaderLayout.createSequentialGroup()
                .addComponent(jPanelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 739, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanelIheaderLayout.setVerticalGroup(
            jPanelIheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIheaderLayout.createSequentialGroup()
                .addGroup(jPanelIheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelIheader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 30));

        jPanelContenido.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelContenidoLayout = new javax.swing.GroupLayout(jPanelContenido);
        jPanelContenido.setLayout(jPanelContenidoLayout);
        jPanelContenidoLayout.setHorizontalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        jPanelContenidoLayout.setVerticalGroup(
            jPanelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(jPanelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 850, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelIheaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelIheaderMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanelIheaderMousePressed

    private void jPanelIheaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelIheaderMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanelIheaderMouseDragged

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        System.exit(0);//salida del programa
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jLabelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseEntered
        jPanelBoton.setBackground(Color.red);
        jLabelCerrar.setForeground(Color.white);
    }//GEN-LAST:event_jLabelCerrarMouseEntered

    private void jLabelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseExited
        jPanelBoton.setBackground(Color.white);
        jLabelCerrar.setForeground(Color.black);
    }//GEN-LAST:event_jLabelCerrarMouseExited
    /**
     * 
     * Boton para cierra de sesion  
     */
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
         Login lg = new Login();
                 lg.setVisible(true);
                 this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked
    /**
     * 
     * Boton para pasar a la página de modificacion de datos 
     */
    private void jLabelDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDatosMouseClicked
        ModificarDatoss md= new ModificarDatoss();
        md.setSize(850, 550);
        md.setLocation(0, 0);
        
        jPanelContenido.removeAll();
        jPanelContenido.add(md,BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
        
    }//GEN-LAST:event_jLabelDatosMouseClicked
    /**
     * 
     * Boton para pasar a la página de busqueda y compra de productos. 
     */
    private void jLabelInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInicioMouseClicked
        BusquedaProductos bp= new BusquedaProductos();
        bp.setSize(850, 550);
        bp.setLocation(0, 0);
        
        jPanelContenido.removeAll();
        jPanelContenido.add(bp,BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }//GEN-LAST:event_jLabelInicioMouseClicked
    /**
     * 
     * Boton para pasar a la página de cesta, para ver todos los productos 
     */
    private void jLabelCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCompraMouseClicked
        MostrarCesta mc= new MostrarCesta();
        mc.setSize(850, 550);
        mc.setLocation(0, 0);
        
        jPanelContenido.removeAll();
        jPanelContenido.add(mc,BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }//GEN-LAST:event_jLabelCompraMouseClicked
    /**
     * 
     * Boton para pasar a la página de opiniones 
     */
    private void jLabelCompra1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCompra1MouseClicked
        Opiniones op= new Opiniones();
        op.setSize(850, 550);
        op.setLocation(0, 0);
        
        jPanelContenido.removeAll();
        jPanelContenido.add(op,BorderLayout.CENTER);
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
                                
    }//GEN-LAST:event_jLabelCompra1MouseClicked


   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelCompra;
    private javax.swing.JLabel jLabelCompra1;
    private javax.swing.JLabel jLabelDatos;
    private javax.swing.JLabel jLabelInicio;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JPanel jPanelIheader;
    private javax.swing.JPanel jPanelNavegador;
    // End of variables declaration//GEN-END:variables
}
