package poo.trabajo.interfaces;

import java.time.LocalDate;
import java.util.ArrayList;
import poo.trabajo.Carro;
import poo.trabajo.Cliente;
import poo.trabajo.Cliente_empresa;
import poo.trabajo.Cliente_particular;
import poo.trabajo.DatosClientes;
import poo.trabajo.DatosProductos;
import java.awt.Color;
import javax.swing.ImageIcon;


/**
 *
 * @author josed y maria
 */

public class Facturas extends javax.swing.JFrame {
    int xMouse,yMouse;
    public String salida = new String();
    ArrayList<Carro> carros = DatosProductos.getCarro();//cargamos el array del carro donde estan almacenados los productos selecionados para comprar.
    /**
     * Creamos la factura 
     */
    public Facturas() {
        initComponents();
        jLabelImg.setIcon(new ImageIcon("./src/main/java/poo/trabajo/imagenes/javacomp.png"));
        salida = salida.concat("-------------------------------- Factura de Compra --------------------------------");
        salida = salida.concat("\n");
        String usuario=Login.usuario;
        Cliente login=DatosClientes.encontrarCliente(usuario);
        int total=5;
        salida = salida.concat("Fecha de la compra: "+LocalDate.now());
        salida = salida.concat("\n");
        salida = salida.concat("El usuaruio es: "+login.getNombre());
        salida = salida.concat("\n");
        salida = salida.concat("El correo es: "+login.getCorreo_electronico());
        salida = salida.concat("\n");
        salida = salida.concat("La direcion es: "+login.getDireccion().toString());
        salida = salida.concat("\n");
        salida = salida.concat("El telefono es: "+login.getTelefono());
        salida = salida.concat("\n");
        salida = salida.concat("Se realizo el pago con la targeta: "+login.getTarjeta().toString());
        salida = salida.concat("\n");
        String s =login.getClass().getSimpleName();
        if (login.getClass().getSimpleName().equals("Cliente_particular")) {//si es particular se muestran los datos relacionados a el 
            Cliente_particular particular = (Cliente_particular) login;
            salida = salida.concat("*** Cliente Particular ***");
            salida = salida.concat("\n");
            salida = salida.concat("Dni: " + particular.getDni());
            salida = salida.concat("\n");
        } else {
            Cliente_empresa empresa = (Cliente_empresa) login;//si es empresa se muestran los datos relacionados a ella
            salida = salida.concat("*** Cliente Empresas ***");
            salida = salida.concat("\n");
            salida = salida.concat("CIF: " + empresa.getCif());
            salida = salida.concat("\n");
            salida = salida.concat("web: " + empresa.getWeb());
            salida = salida.concat("\n");
        }
        salida = salida.concat("-------------------------------- Datos de los Productos --------------------------------");
        salida = salida.concat("\n");
        for (Carro c: carros){
            salida = salida.concat("\n");
            salida = salida.concat("Producto: " +c.getProductos().getTitulo() );
            salida = salida.concat("\n");
            salida = salida.concat("Categoria: " +c.getProductos().getCategoria());
            salida = salida.concat("\n");
            salida = salida.concat("Cantidad: " +c.getCantidad());
            salida = salida.concat("\n");
            salida = salida.concat("Caracteristicas: " +c.getProductos().getCaracteristicas() );
            salida = salida.concat("\n");
            salida = salida.concat("Precio por unidad: " +c.getProductos().getPrecio());
            salida = salida.concat("\n");
            salida = salida.concat("Precio toal del producto: "+c.getProductos().getTitulo()+ " es: " +c.getPrecio()+"€" );
            salida = salida.concat("\n");
            salida = salida.concat("El envio son 5€" );
            salida = salida.concat("\n");
            salida = salida.concat( "-------------------------------- --------- --------------------------------");
            total+=c.getPrecio();
        }   
        salida = salida.concat("\n");
        salida = salida.concat("El precio total con el envio es:  " +total+ "€");
        jTextPane1.setText(salida);
        carros.clear();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jPanelIheader = new javax.swing.JPanel();
        jPanelBoton = new javax.swing.JPanel();
        jLabelCerrar = new javax.swing.JLabel();
        jLabelImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("FACTURA");

        jScrollPane1.setViewportView(jTextPane1);

        jPanelIheader.setBackground(new java.awt.Color(51, 51, 255));
        jPanelIheader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanelIheaderMouseDragged(evt);
            }
        });
        jPanelIheader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanelIheaderMousePressed(evt);
            }
        });

        jLabelCerrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelCerrar.setText("X");
        jLabelCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonLayout = new javax.swing.GroupLayout(jPanelBoton);
        jPanelBoton.setLayout(jPanelBotonLayout);
        jPanelBotonLayout.setHorizontalGroup(
            jPanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jLabelCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelBotonLayout.setVerticalGroup(
            jPanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBotonLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelCerrar))
        );

        javax.swing.GroupLayout jPanelIheaderLayout = new javax.swing.GroupLayout(jPanelIheader);
        jPanelIheader.setLayout(jPanelIheaderLayout);
        jPanelIheaderLayout.setHorizontalGroup(
            jPanelIheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIheaderLayout.createSequentialGroup()
                .addComponent(jPanelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(524, Short.MAX_VALUE))
        );
        jPanelIheaderLayout.setVerticalGroup(
            jPanelIheaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIheaderLayout.createSequentialGroup()
                .addComponent(jPanelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelImg.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelIheader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelIheader, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelImg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseClicked
        EsCliente cl = new EsCliente();//pantalla adminstrador
        cl.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelCerrarMouseClicked

    private void jLabelCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseEntered
        jPanelBoton.setBackground(Color.red);
        jLabelCerrar.setForeground(Color.white);
    }//GEN-LAST:event_jLabelCerrarMouseEntered

    private void jLabelCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCerrarMouseExited
        jPanelBoton.setBackground(Color.white);
        jLabelCerrar.setForeground(Color.black);
    }//GEN-LAST:event_jLabelCerrarMouseExited

    private void jPanelIheaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelIheaderMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanelIheaderMouseDragged

    private void jPanelIheaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelIheaderMousePressed
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanelIheaderMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCerrar;
    private javax.swing.JLabel jLabelImg;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelIheader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
